// MSX-BASIC 組み込み命令・関数の既定表（docs/12）。
// 実装初期は名前集合のみ。将来は設定で編集/リセット可（docs/12 §12.4）。

// 文として使われる組み込み（行頭に来る）
export const BUILTIN_STATEMENTS: ReadonlySet<string> = new Set([
  "PRINT",
  "INPUT",
  "LOCATE",
  "CLS",
  "SCREEN",
  "COLOR",
  "WIDTH",
  "BEEP",
  "PSET",
  "PRESET",
  "LINE",
  "CIRCLE",
  "PAINT",
  "DRAW",
  "SOUND",
  "PLAY",
  "POKE",
  "VPOKE",
  "OUT",
  "WAIT",
  "SET",
  "OPEN",
  "CLOSE",
  "GET",
  "PUT",
  "SPRITE",
  "KEY",
  "FILES",
  "LOAD",
  "SAVE",
  "BLOAD",
  "BSAVE",
  "MAXFILES",
  "DATA",
  "READ",
  "RESTORE",
  "ERASE",
  "CLEAR",
  "SWAP",
  "DEFINT",
  "DEFSNG",
  "DEFDBL",
  "DEFSTR",
  "STOP",
  "END",
]);

// 式中で使われる組み込み関数
export const BUILTIN_FUNCTIONS: ReadonlySet<string> = new Set([
  "ABS",
  "INT",
  "SQR",
  "SIN",
  "COS",
  "TAN",
  "ATN",
  "LOG",
  "EXP",
  "RND",
  "SGN",
  "FIX",
  "LEFT$",
  "RIGHT$",
  "MID$",
  "CHR$",
  "ASC",
  "LEN",
  "VAL",
  "STR$",
  "HEX$",
  "OCT$",
  "BIN$",
  "INSTR",
  "SPACE$",
  "STRING$",
  "INPUT$",
  "INKEY$",
  "SPRITE$",
  "BASE",
  "VDP",
  "PEEK",
  "VPEEK",
  "INP",
  "STICK",
  "STRIG",
  "PAD",
  "PDL",
  "POS",
  "CSRLIN",
  "VARPTR",
  "FRE",
  "TIME",
  "ERR",
  "ERL",
]);

export const isBuiltinStatement = (name: string): boolean =>
  BUILTIN_STATEMENTS.has(name.toUpperCase());
export const isBuiltinFunction = (name: string): boolean =>
  BUILTIN_FUNCTIONS.has(name.toUpperCase());
export const isBuiltin = (name: string): boolean =>
  isBuiltinStatement(name) || isBuiltinFunction(name);
